print( 3 < 5)
print( 5 <= 5)
print("Testing swapping < and > operators")
print( 10 < 5)
print (5 > 10)
print("Test equality")
print (3==3)
print("Test strings")
print( "abc" != "Abc")
print( "abc" == "abc")
print("test type")
print("5" == 5)