print("3 == 3")
print(3 == 3)
print("hat" == "hat")
print("hat" != "hat")
# Comparing strings
print("Compring strings")
print("test: abc < fgh")
print( "abc" < "fgh")
print("fred" < "albert")
print("test: a < ab")
print("a" < "ab")
print("test: ab < a")
print("ab" < "a")
print("test: ab <= a")
print("ab" <= "a")
print(3 < 6)
print(6 > 3)
print("ab" < "a")
print("ab" > "a")