print("A truth table for and")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print()
print("Or truth table")
print(True or True)
print(True or False)
print(False or True)
print(False or False)

